# Generated by Django 4.1.1 on 2022-10-21 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userinfo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('course_type', models.CharField(choices=[('diploma', 'Diploma Engineering'), ('trade', 'Trade Course')], max_length=100)),
                ('course_name', models.CharField(choices=[('DEMT', 'Diploma In Engineering Marine Technology'), ('DEST', 'Diploma In Engineering Shipbuilding Technology'), ('MDEA', 'Marine Diesel Engine Artificer'), ('SF', 'Ship Fabrication'), ('SBW', 'Shipbuilding Welding'), ('SBMD', 'Shipbuilding and Mechanical Draftsmanship')], max_length=25)),
                ('intake_name', models.CharField(max_length=25)),
                ('bimt_passing_year', models.IntegerField(blank=True, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(choices=[('ISLAM', 'Islam'), ('HINDU', 'Hindu'), ('CHRISTIAN', 'Christian'), ('BUDDHIST', 'Buddhist'), ('OTHERS', 'Others')], max_length=50)),
                ('gendar', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=50)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=50)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single'), ('DIVORCED', 'Divorced')], max_length=50)),
                ('ecp', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no_ecp', models.CharField(blank=True, max_length=100, null=True)),
                ('relation_with_ecp', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=350)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_service', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='ProfessionalSkills',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('skill_logo', models.URLField(max_length=250)),
                ('skill_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_skill', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='PresentAddress',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('care_of', models.CharField(max_length=200)),
                ('house_no', models.CharField(max_length=200)),
                ('road_name', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('ward_no', models.CharField(max_length=200)),
                ('post_office', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=200)),
                ('police_station', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='present_address', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='PortfolioInfo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Un-employed'), ('business', 'Business')], max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('about_me', models.CharField(max_length=250)),
                ('profile_img', models.ImageField(default='default.jpg', help_text='File size should be less than 2mb(.jpg/.png/.gif)', upload_to='profile_img/', validators=[userinfo.models.file_size])),
                ('banner_image', models.ImageField(help_text='File size should be less than 2mb(.jpg/.png/.gif)', upload_to='banner_img/', validators=[userinfo.models.file_size])),
                ('footer_image', models.ImageField(help_text='File size should be less than 2mb(.jpg/.png/.gif)', upload_to='footer_img/', validators=[userinfo.models.file_size])),
                ('facebook_id', models.URLField()),
                ('linked_id', models.URLField()),
                ('github_id', models.URLField()),
                ('cv_link', models.URLField(max_length=350)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_info', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('project_name', models.CharField(max_length=150)),
                ('project_img', models.URLField(max_length=350)),
                ('preview_link', models.URLField(max_length=350)),
                ('github_link', models.URLField(max_length=350)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('care_of', models.CharField(max_length=200)),
                ('house_no', models.CharField(max_length=200)),
                ('road_name', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('ward_no', models.CharField(max_length=200)),
                ('post_office', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=200)),
                ('police_station', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='Experince',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('company_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('join_year', models.IntegerField()),
                ('resign_year', models.IntegerField()),
                ('responsibility', models.TextField(max_length=350)),
                ('company_logo', models.URLField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_experience', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('degree_name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('institute', models.CharField(max_length=250)),
                ('start_year', models.IntegerField()),
                ('passing_year', models.IntegerField()),
                ('short_brief', models.TextField(max_length=350)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_education', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField(max_length=350)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_request', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('client_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('client_photo', models.URLField(max_length=350)),
                ('job_title', models.CharField(max_length=250)),
                ('market_place', models.CharField(max_length=150)),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField()),
                ('rating', models.FloatField()),
                ('feedback', models.TextField(max_length=350)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
    ]
