# Generated by Django 4.1.1 on 2022-10-24 16:17

from django.db import migrations, models
import userinfo.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permanentaddress',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='presentaddress',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='portfolioinfo',
            name='profile_img',
            field=models.ImageField(default='profile_img/default.jpg', help_text='File size should be less than 2mb(.jpg/.png/.gif)', upload_to='profile_img/', validators=[userinfo.models.file_size]),
        ),
    ]
